[CPDNPQ-2170] Re-add the git sha check and include a sleep
Sleep's are rarely the correct answer but in this instance we need to
allow time for the old apps to drain before hitting the healthcheck
endpoint

The impact is to add 10 secs to a deploy which isn't too bad

diff --git a/bin/smoke b/bin/smoke
--- a/bin/smoke
+++ b/bin/smoke
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+sleep 10 # Allow time for old app instances to drain
+
 url=$1
 if [[ -z $url ]]; then
   echo `date`" - smoke test failed (URL is missing)"
@@ -11,6 +13,13 @@ response_sha=$(jq ".git_commit_sha" <<< $response)
 current_commit_sha=\"$2\"
 if [[ -z $current_commit_sha ]]; then
   echo `date`" - smoke test failed (head sha is missing)"
+  exit 1
+fi
+
+if [[ $response_sha == $current_commit_sha ]]; then
+  echo "✅ Correct version deployed"
+else
+  echo "Fail: healthcheck sha is $response_sha but current commit is $current_commit_sha"
   exit 1
 fi
 
